name = "chitchatter-nodecrypt"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"
script_name = "chitchatter-nodecrypt"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
